<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEn7NdTB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEn7NdTB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEn7NdTB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEn7NdTB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEn7NdTB\App_KernelDevDebugContainer([
    'container.build_hash' => 'En7NdTB',
    'container.build_id' => '8090b242',
    'container.build_time' => 1629708389,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEn7NdTB');
