<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQGmGdMR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQGmGdMR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQGmGdMR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQGmGdMR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQGmGdMR\App_KernelDevDebugContainer([
    'container.build_hash' => 'QGmGdMR',
    'container.build_id' => 'a11056d5',
    'container.build_time' => 1629977229,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQGmGdMR');
